function ANALYSIS_DISTANCE()

populate(LICK2D.DistancePSTHCorrVolumetricSpikes)
populate(LICK2D.DistanceQuadrantsCorrVolumetricSpikes)
populate(LICK2D.DistanceAngularTuningCorrVolumetricSpikes)
populate(LICK2D.DistanceAngleSpikes)

population_DistanceTuning