
% Behavior data
lick2D_behaviorperform
lick2D_video_licking_stats
lick2D_video_yawmemory_across_blocks


% Neural data
lick2D_map_onFOV_corr
lick2D_map_onFOV_angles
lick2D_map_onFOV_clusters
lick2D_map_onFOV_clusters_selectivity
lick2D_map_onFOV_clusters_shapeandselectivity
lick2D_map
lick2D_map_meso
lick2D_map_photostim



lick2D_map_onFOV_clusters_shapeandselectivity_meso
lick2D_map_onFOV_clusters_shape_meso
lick2D_map_onFOV_clusters_selectivity_meso

lick2D_local_corr_map
lick2D_map_onFOV_angles__meso
lick2D_map_onFOV_angles__meso_neuropil
