


% Behavior data
lick2D_behaviorperform
lick2D_behaviorperform_numlicks
lick2D_video_licking_stats
lick2D_video_licking_stats_reward_increase_omission
lick2D_video_yawmemory_across_blocks
lick2D_video_yawmemory_across_blocks2 % that's what was shown in the original presentation
lick2D_video_yaw_early_vs_nonearly % that's what was shown in the original presentation
lick2D_video_yaw_early_vs_nonearly2
lick2D_video_yaw_trajectory
lick2D_video_yaw_learning

% Neural data Reward
PLOTS_Population2DReward_all_sessions
PLOTS_Population2DReward_all_sessions___vsPoisson
PLOTS_Population2DReward_all_sessions___vsPoisson__sum


% Neural data
lick2D_map_onFOV_corr
lick2D_map_onFOV_angles
lick2D_map_onFOV_clusters
lick2D_map_onFOV_clusters_selectivity
lick2D_map_onFOV_clusters_shapeandselectivity
lick2D_map
lick2D_map_meso
lick2D_map_photostim



lick2D_map_onFOV_clusters_shapeandselectivity_meso
lick2D_map_onFOV_clusters_shape_meso
lick2D_map_onFOV_clusters_selectivity_meso

lick2D_local_corr_map
lick2D_map_onFOV_angles__meso
lick2D_map_onFOV_angles__meso_neuropil
